### ISSUE TITLE
How can i print the tag name that is being created

### ISSUE THREAD

**Issue by tarangrathod** [christophebedard/tag-version-commit#461]
how can do this 
i want to get the tag name that is getting created so to further use in docker container tagging

**Comment by christophebedard** [comment]
The tag name is provided as an output (see `tag`): https://github.com/christophebedard/tag-version-commit#outputs

You can use it like this:

```
    - uses: christophebedard/tag-version-commit@v1
      id: tag-version-commit
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "${{ steps.tag-version-commit.outputs.tag }}"
```
